### ISSUE TITLE
Check if a Validation Error still Exists

### ISSUE THREAD

**Issue by ghost** [AIexandr/Caliburn.Micro.Validation#2]
How do I check if a validation error still exists?

Is there a property or method that I can use to check for existing validation errors?

It would be very convenient if there is a `HasError` property (or something similar) that will indicate that there are still validation errors. We can then bind this property to the `IsEnabled` property of a button and use a converter to invert the value so that the button will only be clickable if there are no validation errors left. Or just return `!HasError` in the `CanButtonName` method. :smile:

**Comment by AIexandr** [comment]
Just added.
But it is not good idea to use a converter when using MVVM - just add another property to your VM;)

**Comment by ghost** [comment]
Thank you very much. I tried it last night and it worked great on my project. :smiley:

**Comment by AIexandr** [comment]
You are welcome!
